[server]
headless = true
# Note: Port and address are NOT specified here for cloud deployment
# This allows Streamlit Cloud to handle port assignment automatically

[theme]
primaryColor = "#4a90e2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f8fa"
textColor = "#212529"
font = "sans serif"